### ISSUE TITLE
【ベクトル・行列入門】「『補足　ベクトルの本質について』の説明文」文言修正

### ISSUE THREAD

**Issue by kakiuchis** [DiveintoCode-corp/ai-course#11]
『補足　ベクトルの本質について』の説明文内での脱字です。
※細かい内容で申し訳ないです。

[誤]そして矢印であることを説明すべきですが、この章では取扱ません。

[正]そして矢印であることを説明すべきですが、この章では取扱いません。

**Comment by choochoopiston** [comment]
プルリク済み。よく気づきましたね、さすがです！ありがとうございます。
