### ISSUE TITLE
【ベクトル・行列入門】「『ベクトル』の計算例」文言修正

### ISSUE THREAD

**Issue by kakiuchis** [DiveintoCode-corp/ai-course#12]
『ベクトル』の計算例（2箇所）にて、計算式と計算式の間にスペースがあると見やすいです。
『45+45+=330』となっている。
※細かい内容で申し訳ないです。

[誤①]67+67=13476+76=15245+45+=330
[誤②]3*2=63*10=303*20=60

[正①]67+67=134  76+76=152  45+45=90
[正②]3x2=6  3x10=30  3x20=60

**Comment by choochoopiston** [comment]
プルリク済み。
