### ISSUE TITLE
【人工知能概論（事例編）】「車の自動運転」文言修正、画像修正

### ISSUE THREAD

**Issue by kakiuchis** [DiveintoCode-corp/ai-course#19]
「車の自動運転」の説明文の最後に「[!」がついている。
gyazoの画像URLがありますが、おそらく想定のステータスとしては画像が表示されているのかと思いまして。

[誤]
画像認識などに特化したディープラーニングが使用されます。[!
https://diveintocode.gyazo.com/629184d245a97bb9333f84c197570e91]
(https://diveintocode.gyazo.com/629184d245a97bb9333f84c197570e91)

[正]
画像認識などに特化したディープラーニングが使用されます。
≪ここに画像が表示される≫

**Comment by choochoopiston** [comment]
プルリク済み
