### ISSUE TITLE
【人工知能概論（事例編）】「課題」文言修正

### ISSUE THREAD

**Issue by kakiuchis** [DiveintoCode-corp/ai-course#20]
「課題」の説明文の最後の方に、HTMLのコード（href=・・・）が露出している。

[誤]
実世界の人工知能 〜交通，製造業，バイオヘルスケア〜 from
href="//www.slideshare.net/pfi">Preferred Infrastructure & Preferred Networks

[正]
実世界の人工知能 〜交通，製造業，バイオヘルスケア〜 from Preferred Infrastructure & Preferred Networks
※リンク先は「https://www.slideshare.net/pfi」が想定している場所でしょうか。

**Comment by choochoopiston** [comment]
すでに修正されていました。ありがとうございます。
