### ISSUE TITLE
【Think Like a AI Engineer DRY編】「同じ処理を繰り返さないということ」コード修正

### ISSUE THREAD

**Issue by kakiuchis** [DiveintoCode-corp/ai-course#25]
「同じ処理を繰り返さないということ」のget_linkメソッドの引数の文字列の「"」が二重に使用されている。

[誤]
get_link("＜a class="nav" href="/teachers"＞講師紹介</a></li>")
get_link("＜a href="https://en.wikipedia.org/wiki/Andy_Hunt"＞Andy Hunt</span></a>")
get_link("＜a class="nav" href="/ai_course"＞AIコース</a></li>")

[正]
get_link('＜a class="nav" href="/teachers"＞講師紹介</a></li>')

get_link('＜a href="https://en.wikipedia.org/wiki/Andy_Hunt"＞Andy Hunt</span></a>')

get_link('＜a class="nav" href="/ai_course"＞AIコース</a></li>')

**Comment by choochoopiston** [comment]
プルリク済み
