### ISSUE TITLE
【Think Like a AI Engineer DRY編】「課題」コード修正

### ISSUE THREAD

**Issue by kakiuchis** [DiveintoCode-corp/ai-course#26]
「課題」の共通化前のコードですが、
この状況ですと、そもそも何も表示されないので、
共通化の成功失敗が明確に判断できるよう、
何らかの形に変更すべきかもしれないです。

例えば下記のような形でしょうか。

[誤]
ryuji = 29
hiroomi = 29
taro = 29
ziro = 29
ichiro = 29
niro = 29

[正]
ryuji = 31

hiroomi = 29
taro = 31
ziro = 30
ichiro = 29
niro = 25

**Comment by choochoopiston** [comment]
プルリク済み
