### ISSUE TITLE
【スクレイピング3】「小課題5」以降、コード修正

### ISSUE THREAD

**Issue by choochoopiston** [DiveintoCode-corp/ai-course#30]
コード例内に誤りがありました。小課題5以降も、同じ間違いが各小課題で繰り返されています。

[誤] if number == -1
[正] if href_number == -1

**Comment by kakiuchis** [comment]
小課題5の少し前の「text.find("href=")できなかった場合の処理を修正する」のコード内も「if number == -1」→「if href_number == -1」ですね！何卒よろしくお願いいたします。

**Comment by choochoopiston** [comment]
そうですね、ありがとうございます。
