### ISSUE TITLE
【機械学習概論】「機械学習とは」文言修正

### ISSUE THREAD

**Issue by kakiuchis** [DiveintoCode-corp/ai-course#36]
機械学習の流れの項番が間違っている

[誤]
①自分の扱いたい問題に関するデータを集め、適切な形に前処理する。
②前処理が終わった膨大な元の情報から予測のために必要な本質的な情報（特徴量）を抽出する。
②予測のための機械学習の「モデル」を用意する。
③データ（特徴量）を「モデル」に入力し学習をさせる。
④学習済みのモデルの性能を評価する。
④最後に、学習済みのモデルに未知のデータを入力し、予測をさせる。
[正]
①自分の扱いたい問題に関するデータを集め、適切な形に前処理する。
②前処理が終わった膨大な元の情報から予測のために必要な本質的な情報（特徴量）を抽出する。
③予測のための機械学習の「モデル」を用意する。
④データ（特徴量）を「モデル」に入力し学習をさせる。
⑤学習済みのモデルの性能を評価する。
⑥最後に、学習済みのモデルに未知のデータを入力し、予測をさせる。

**Comment by choochoopiston** [comment]
ありがとうございます。プルリク済みです。
