### ISSUE TITLE
【アルゴリズム入門　演習】「合格要件」文言変更

### ISSUE THREAD

**Issue by kakiuchis** [DiveintoCode-corp/ai-course#40]
30と20の最大公約数は10かもしれない。。

[誤]2, greatest_common_divisor(30, 20)のように引数を渡すと、最大公約数が返却される（この場合20が返却される）
[正]2, greatest_common_divisor(30, 20)のように引数を渡すと、最大公約数が返却される（この場合10が返却される）

**Comment by choochoopiston** [comment]
ありがとうございます。プルリク済みです。
