### ISSUE TITLE
【アルゴリズム入門３】「実際にコードを記述する」

### ISSUE THREAD

**Issue by katoyuki1** [DiveintoCode-corp/ai-course#41]
変数a、bにそれぞれ値を代入しているのに、bigger関数に数字1、2を渡している。

(現在)
a = 1
b = 2

bigger(1, 2)

(修正案)
a = 1
b = 2

bigger(a, b)

**Comment by choochoopiston** [comment]
ありがとうございます。プルリク済みです。
